name: AndroidBuild

on: [push]

jobs:
  editorTestJob:
    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ matrix.unity-tag }}
    strategy:
      matrix:
        unity-tag: [2019.2.9f1-android]

    steps:
    - uses: actions/checkout@master
    - run: openssl aes-256-cbc -d -in Unity_v2019.x.ulf-cipher -k ${CYPHER_KEY} -md md5 >> ./License.ulf
      env:
          CYPHER_KEY: ${{ secrets.CYPHER_KEY }}
    - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile ./License.ulf || exit 0
    - run: |
          CURRENT_DIR=`pwd`
          echo ${CURRENT_DIR}
          /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath GithubActions -executeMethod Builder.AndroidBiild -outputPath ${CURRENT_DIR}/Android/android.apk || exit 0
    - uses: actions/upload-artifact@master
      with:
        name: AndroidBuild
        path: Android
    
